#!/bin/bash

echo "🚀 MIS Analytics Platform - Deploy to Render"
echo "============================================="

echo ""
echo "📂 Your code is already on GitHub at:"
echo "https://github.com/chethanwizo/MSI.git"

echo ""
echo "✅ Code is ready for deployment!"

echo ""
echo "🎯 Deployment Steps:"
echo ""

echo "1. 🌐 Create Web Service on Render:"
echo "   • Go to https://render.com"
echo "   • Sign up/Login with GitHub"
echo "   • Click 'New +' → 'Web Service'"
echo "   • Connect GitHub repo: chethanwizo/MSI"
echo "   • Name: mis-analytics-backend"
echo "   • Runtime: Node"
echo "   • Build Command: cd backend && npm install && npx prisma generate"
echo "   • Start Command: cd backend && npm start"
echo "   • Plan: Free"
echo ""

echo "2. 🔧 Set Environment Variables in Render:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   DATABASE_URL=postgresql://postgres:Ertfgh5500@db.tcepvwfzvfinimywvkfa.supabase.co:5432/postgres"
echo "   JWT_SECRET=mis-analytics-platform-super-secret-jwt-key-2024-production-render"
echo "   JWT_EXPIRES_IN=7d"
echo "   MAX_FILE_SIZE=10485760"
echo "   UPLOAD_DIR=uploads"
echo "   FRONTEND_URL=https://your-vercel-app.vercel.app"
echo ""

echo "3. 🚀 Deploy Backend:"
echo "   • Click 'Create Web Service'"
echo "   • Wait for deployment (5-10 minutes)"
echo "   • Go to Shell tab and run: npm run render:setup"
echo ""

echo "4. 🌐 Deploy Frontend to Vercel:"
echo "   Run these commands:"
echo "   npm install -g vercel"
echo "   vercel login"
echo "   cd frontend"
echo "   vercel"
echo ""
echo "   Then set environment variable in Vercel dashboard:"
echo "   NEXT_PUBLIC_API_URL=https://your-render-service.onrender.com/api"
echo ""

echo "5. 🔗 Update CORS:"
echo "   • Get your Vercel URL"
echo "   • Update FRONTEND_URL in Render environment variables"
echo ""

echo "🎉 Your platform will be live at:"
echo "Backend: https://your-service.onrender.com"
echo "Frontend: https://your-app.vercel.app"
echo ""
echo "Default login: admin@example.com / password123"
echo ""
echo "📖 For detailed instructions, see: RENDER_DEPLOYMENT.md"